### ISSUE TITLE
Initial review of this repo

### ISSUE THREAD

**Issue by manics** [IDR/idr-analysis.openmicroscopy.org#1]
Review the new idr-analysis website.

Testing:
```
docker pull imagedata/idr-analysis.openmicroscopy.org
docker run -it --rm -p 8080:80 imagedata/idr-analysis.openmicroscopy.org
```
http://localhost:8080/

Or https://idr-analysis.openmicroscopy.org/ if github-gitlab mirroring is fixed, otherwise the version deployed there will be https://github.com/IDR/idr-analysis.openmicroscopy.org/commit/b3a017745acb471f29f1bddf3df4ef22a58cebdb

This only contains the static content for idr-analysis, so links to Jupyterhub won't work when testing the docker image locally.

**Comment by manics** [comment]
Two issues already reported by @jburel:
- [x] ` immense range`: diverse and vast range
- [x] `Please note we`: Please note that we ...

**Comment by joshmoore** [comment]
Various comments:

### top-matter
 * The name/tagline has changed, no? If we're moving away from VAE, we will need to have some unification.
 * "It is built" ... perhaps "provides" if we want to provide
 * Can we say anything about restarts (i.e. loss of data)?

**Comment by manics** [comment]
Do you have any suggested text for the name/tagline?

**Comment by manics** [comment]
See https://github.com/IDR/idr-analysis.openmicroscopy.org/pull/2
